db:
    drivers:
        default:
            file: ./database/app.db
            maxidleconns: 10
            maxopenconns: 100
            type: sqlite
mongodb:
    drivers:
        default:
            dbname: duxgo
            host: localhost
            password: ""
            port: 27017
            username: ""
redis:
    drivers:
        default:
            db: 0
            host: localhost
            password: ""
            port: 6379
