db:
  drivers:
    default:
      type: mysql
      host: localhost
      database: duxgo
      username: root
      password: root
      port: '3306'
      maxIdleConns: 10
      maxOpenConns: 100
mongodb:
  drivers:
    default:
      host: localhost
      port: 27017
      dbname: duxgo
      username: ""
      password: ""
redis:
  drivers:
    default:
      db: 0
      host: localhost
      password: ""
      port: 6379
