app:
    debug: true
    domain: http://localhost
    lang: zh-CN
    name: Dux
    secret: NKYYCXTXDYOJCIQHDGWYBQCAYTPZLFLW
manage:
    indexname: cms
server:
    port: 8900
    timeout: 30
vite:
    port: 5173
